### ISSUE TITLE
ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by swap83** [lucadentella/raspberry-dgc#35]
Ubuntu 20.04.3 Server 
Se si volesse utilizzare un PC ed utilizzare solo la parte validatorServer cosa devo installare?
Pur non avendo nessun errore quando faccio 
`npm install`

al momento di fare 
`node app.js`

ricevo questo errore:

```
root@green-pass:/var/www/raspberry-dgc/validatorServer# node app.js
/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.cbor=t():e.cbor=t()}(this,(function(){return(()=>{var e={742:(e,t)=>{"use strict";t.byteLength=function(e){var t=u(e),r=t[0],n=t[1];return 3*(r+n)/4-n},t.toByteArray=function(e){var t,r,o=u(e),s=o[0],a=o[1],f=new i(function(e,t,r){return 3*(t+r)/4-r}(0,s,a)),h=0,l=a>0?s-4:s;for(r=0;r<l;r+=4)t=n[e.charCodeAt(r)]<<18|n[e.charCodeAt(r+1)]<<12|n[e.charCodeAt(r+2)]<<6|n[e.charCodeAt(r+3)],f[h++]=t>>16&255,f[h++]=t>>8&255,f[h++]=255&t;return 2===a&&(t=n[e.charCodeAt(r)]<<2|n[e.charCodeAt(r+1)]>>4,f[h++]=255&t),1===a&&(t=n[e.charCodeAt(r)]<<10|n[e.charCodeAt(r+1)]<<4|n[e.charCodeAt(r+2)]>>2,f[h++]=t>>8&255,f[h++]=255&t),f},t.fromByteArray=function(e){for(var t,n=e.length,i=n%3,o=[],s=16383,a=0,u=n-i;a<u;a+=s)o.push(f(e,a,a+s>u?u:a+s));return 1===i?(t=e[n-1],o.push(r[t>>2]+r[

ReferenceError: TextDecoder is not defined
    at Object.202 (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:59485)
    at r (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:115570)
    at Object.873 (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:56222)
    at r (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:115570)
    at Object.20 (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:27297)
    at r (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:115570)
    at Object.141 (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:26717)
    at r (/var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:115570)
    at /var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:116537
    at /var/www/raspberry-dgc/validatorServer/node_modules/cbor-web/dist/cbor.js:2:116545
```

**Comment by swap83** [comment]
Ho inserito in testa a cbor.js  questa stringa
`const { TextEncoder, TextDecoder } = require("util");`

ed il "server" si è avviato

`root@green-pass:/var/www/raspberry-dgc/validatorServer# node app.js
validatorServer 1.0.0

ADD_HOLDER_DETAILS:  enabled
ADD_DETAILED_MESSAGE:  enabled
Updating keys, settings and blacklist... done!
Automatic update scheduled

validatorServer ready for requests...`

**Comment by lucadentella** [comment]
grazie, l'ho segnalato allo sviluppatore dell'SDK perché la libreria è utilizzata da tale framework
