### ISSUE TITLE
Errore nell'avvio del validator server

### ISSUE THREAD

**Issue by Cipppo** [lucadentella/raspberry-dgc#36]
Salve, ho appena installato tutto il necessario per avviare il server e il client, ma all'avvio del server (tramite node.js) viene restituita un'eccezione (Allego l'output di errore), come posso risolvere ? 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'verificac19-sdk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/c1pp0/Desktop/greenPass/raspberry-dgc/validatorServer/app.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Cipppo** [comment]
Sono riuscito a risolvere in autonomia scricando prima con apt il pacchetto npm, poi eseguendo "npm install" nella cartella del server.
In seguito è stato generato un secondo errore che ho potuto risolvere seguendo un altro thread di questo forum.
